"""StoryFacets domain model — multi-dimensional story classification.

This module defines the faceted classification system that replaces
rigid genre presets with flexible, AI-driven story dimension combinations.
"""

from __future__ import annotations

import re
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator

_CJK_OR_WORD = re.compile(r"[一-鿿]|[A-Za-z0-9]+")


def _char_bigrams(text: str) -> set[str]:
    """Char-bigram set of a (Chinese) string for fuzzy overlap comparison.

    Chinese has no word boundaries, so token-level Jaccard is meaningless;
    char-bigrams capture "how much concrete premise text is shared" robustly.
    Latin runs are kept whole as single tokens. Returns an empty set for blank
    input so callers can treat "no setting" as "no evidence".
    """
    tokens = _CJK_OR_WORD.findall(text or "")
    if len(tokens) < 2:
        return set(tokens)
    return {tokens[i] + tokens[i + 1] for i in range(len(tokens) - 1)}


# ──────────────────────────────────────────────────────────────────────
# Dimension metadata (loaded from config/facets/dimensions.yaml)
# ──────────────────────────────────────────────────────────────────────


class FacetDimensionValue(BaseModel):
    """A single allowed value within a dimension."""

    key: str = Field(min_length=1, max_length=120)
    label_zh: str = Field(default="", max_length=200)
    label_en: str = Field(default="", max_length=200)
    description: str = Field(default="", max_length=500)
    heat_score: int = Field(default=50, ge=0, le=100)


class FacetDimension(BaseModel):
    """Definition of a single facet dimension (e.g., tone, narrative_drive)."""

    name: str = Field(min_length=1, max_length=64)
    label_zh: str = Field(default="", max_length=120)
    label_en: str = Field(default="", max_length=120)
    description: str = Field(default="", max_length=500)
    required: bool = Field(default=False)
    allow_freeform: bool = Field(default=False)
    max_values: int = Field(default=1, ge=1, le=10)
    values: list[FacetDimensionValue] = Field(default_factory=list)


# ──────────────────────────────────────────────────────────────────────
# StoryFacets — the core multi-dimensional story specification
# ──────────────────────────────────────────────────────────────────────


class StoryFacets(BaseModel):
    """Multi-dimensional story classification.

    User provides only `primary_genre` + `language`.
    All other fields are generated by the Story Architect Agent.
    """

    # ── User-provided (required) ──
    primary_genre: str = Field(min_length=1, max_length=120)
    language: str = Field(default="zh-CN", min_length=2, max_length=20)

    # ── AI-generated dimensions ──
    sub_genres: tuple[str, ...] = Field(default_factory=tuple)
    setting: str = Field(default="", max_length=500)
    tone: str = Field(default="balanced", max_length=64)
    power_system: str | None = Field(default=None, max_length=120)
    relationship_mode: str = Field(default="no-cp", max_length=64)
    narrative_drive: str = Field(default="progression", max_length=64)
    emotional_register: str = Field(default="balanced", max_length=64)
    trope_tags: tuple[str, ...] = Field(default_factory=tuple)
    platform_style: str | None = Field(default=None, max_length=64)
    gender_channel: str | None = Field(default=None, max_length=20)

    # ── Metadata ──
    generation_source: Literal["ai", "legacy", "manual"] = Field(default="ai")

    @field_validator("sub_genres", mode="before")
    @classmethod
    def coerce_sub_genres(cls, v: Any) -> tuple[str, ...]:
        if isinstance(v, (list, tuple)):
            return tuple(v)[:3]
        return v

    @field_validator("trope_tags", mode="before")
    @classmethod
    def coerce_trope_tags(cls, v: Any) -> tuple[str, ...]:
        if isinstance(v, (list, tuple)):
            return tuple(v)[:8]
        return v

    def similarity_score(self, other: StoryFacets) -> float:
        """Surface-level duplication score (0.0 = distinct premise, 1.0 = same book).

        Used by the anti-repetition mechanism in the Story Architect Agent.

        CRITICAL — this measures whether two books are the SAME BOOK (same premise
        skin), NOT whether they share a genre. Same-genre books are EXPECTED to
        share the SPINE (tone family, narrative_drive, power-system kind, core
        power-fantasy tropes) — that spine *is* the genre. Weighting spine matches
        heavily (the old design) meant every new same-genre book scored "too
        similar" to prior ones, and the anti-repetition retry then forced it to
        abandon the spine to look different — the cross-book contamination that
        drifted 仙侠升级 into 克系/无金手指. So spine dimensions carry near-zero
        weight; the SURFACE (the concrete `setting` + the specific sub_genre /
        trope combination) carries the weight. Two same-genre books with distinct
        settings score LOW (correctly "not duplicates"); only a genuinely copied
        premise scores high.
        """
        score = 0.0
        total_weight = 0.0

        # Spine dimensions — shared within a genre BY DESIGN → near-zero weight.
        for field_name, weight in [
            ("tone", 0.1),
            ("narrative_drive", 0.1),
            ("relationship_mode", 0.1),
            ("emotional_register", 0.1),
            ("power_system", 0.1),
        ]:
            total_weight += weight
            if getattr(self, field_name) == getattr(other, field_name):
                score += weight

        # Set-like fields — the specific premise combination (surface-ish).
        for field_name, weight in [
            ("sub_genres", 0.5),
            ("trope_tags", 1.0),
        ]:
            total_weight += weight
            self_set = set(getattr(self, field_name))
            other_set = set(getattr(other, field_name))
            if self_set or other_set:
                jaccard = len(self_set & other_set) / len(self_set | other_set)
            else:
                # Both empty → identical on this dimension (preserves 1.0 for
                # identical facets; real AI facets are never empty here).
                jaccard = 1.0
            score += weight * jaccard

        # Setting — the single strongest "same premise?" signal. Char-bigram
        # Jaccard so different concrete worlds read as distinct even when the
        # genre spine is identical. Only counts when BOTH settings are present
        # (an empty setting is no evidence of duplication, so it is skipped).
        self_bigrams = _char_bigrams(self.setting)
        other_bigrams = _char_bigrams(other.setting)
        if self_bigrams and other_bigrams:
            setting_weight = 3.0
            total_weight += setting_weight
            overlap = len(self_bigrams & other_bigrams) / len(
                self_bigrams | other_bigrams
            )
            score += setting_weight * overlap

        return score / total_weight if total_weight > 0 else 0.0


# ──────────────────────────────────────────────────────────────────────
# Dimensions catalog (loaded from YAML)
# ──────────────────────────────────────────────────────────────────────


class FacetDimensionsCatalog(BaseModel):
    """Full catalog of all facet dimensions loaded from config."""

    dimensions: list[FacetDimension] = Field(default_factory=list)

    def get_dimension(self, name: str) -> FacetDimension | None:
        for dim in self.dimensions:
            if dim.name == name:
                return dim
        return None

    def get_valid_keys(self, dimension_name: str) -> set[str]:
        dim = self.get_dimension(dimension_name)
        if dim is None:
            return set()
        return {v.key for v in dim.values}

    def get_hot_tags(self, dimension_name: str, top_n: int = 20) -> list[str]:
        """Return top N values sorted by heat_score descending."""
        dim = self.get_dimension(dimension_name)
        if dim is None:
            return []
        sorted_values = sorted(dim.values, key=lambda v: v.heat_score, reverse=True)
        return [v.key for v in sorted_values[:top_n]]
