#!/usr/bin/env python3
"""Mode B chapter bridge CLI — drive one Mode B chapter through the pipeline.

The dialogue orchestrator (Mode B) calls this in its WRITE_CHAPTER state so
the chapter is generated by the real ``run_chapter_pipeline`` (gates +
scoring + repair) instead of being written by hand. The script syncs
``progress.yaml`` with database truth and exits non-zero when the chapter
needs a rewrite, so the orchestrator routes to REWRITE_CHAPTER.

Usage:
  python3 scripts/mode_b_chapter_bridge.py --slug fen-xin-jue --chapter 7
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO / "src") not in sys.path:
    sys.path.insert(0, str(_REPO / "src"))

from bestseller.infra.db.session import session_scope
from bestseller.services.mode_b_bridge import (
    ModeBBridgeError,
    drive_mode_b_chapter,
    sync_progress_yaml,
)
from bestseller.settings import load_settings


async def _run(slug: str, chapter: int, *, chapter_first: bool) -> int:
    settings = load_settings()
    async with session_scope(settings) as session:
        try:
            outcome = await drive_mode_b_chapter(
                session,
                settings,
                slug,
                chapter,
                chapter_first=chapter_first,
            )
        except ModeBBridgeError as exc:
            print(json.dumps({"error": str(exc)}, ensure_ascii=False, indent=2))
            return 3

    sync_progress_yaml(
        slug,
        outcome,
        output_base_dir=str(settings.output.base_dir),
    )
    print(json.dumps(outcome.to_dict(), ensure_ascii=False, indent=2))
    return 0 if outcome.passed else 2


def main() -> int:
    parser = argparse.ArgumentParser(description="Mode B chapter bridge")
    parser.add_argument("--slug", required=True)
    parser.add_argument("--chapter", type=int, required=True)
    parser.add_argument(
        "--scene-first",
        action="store_true",
        help="Use scene-by-scene generation instead of chapter-first.",
    )
    args = parser.parse_args()
    return asyncio.run(
        _run(args.slug, args.chapter, chapter_first=not args.scene_first)
    )


if __name__ == "__main__":
    raise SystemExit(main())
