"""The hook signal list must not count a genre's own setting vocabulary.

``_HOOK_SIGNALS`` contained the bare character 「门」. Counting is substring
based, so in any 宗门-structured story — 仙侠, 武侠, most 玄幻 — every 内门,
外门, 门派, 门槛, 门帘, 入门 and 出门 registered as a narrative hook.

Measured 2026-07-26 on xianxia-upgrade-1785036205 ch1 (2427 chars): the gate
reported ``hooks=22, payoffs=3, payoff_density=0.12`` and the verdict "chapter
teases without landing". **All 22 hooks were 「门」**; every one of the other
ten signals scored zero. The chapter contained no detected narrative hook at
all, and the gate's entire verdict was noise generated by the setting.

Same failure as the naming pool, the LINE_GAP acceptance gate and the opening
anomaly proxy: a lexical counter that a genre's ordinary vocabulary saturates.
A hook signal must denote an *event*, never a place or an organisational unit.
"""

from __future__ import annotations

import pytest

from bestseller.services.payoff_ledger_gate import (
    _HOOK_SIGNALS,
    evaluate_payoff_ledger,
)

pytestmark = pytest.mark.unit


class TestSectVocabularyIsNotAHook:
    def test_bare_door_character_is_not_a_signal(self) -> None:
        assert "门" not in _HOOK_SIGNALS, (
            "「门」 is a morpheme in 内门/外门/门派/门槛/门帘; as a bare "
            "substring it counts the setting, not a hook"
        )

    @pytest.mark.parametrize(
        "phrase",
        ["内门", "外门", "宗门", "门派", "门槛", "门帘", "入门", "出门", "山门"],
    )
    def test_sect_and_scenery_compounds_score_zero(self, phrase: str) -> None:
        assert not any(signal in phrase for signal in _HOOK_SIGNALS), (
            f"{phrase} is setting vocabulary and must not register as a hook"
        )

    def test_the_live_chapter_shape_no_longer_reports_a_false_verdict(self) -> None:
        """Reconstructed from the real ch1: sect words, no actual hooks."""

        text = (
            "他替内门弟子扛债，也替外门的、坊市的。三年前他刚入门派时曾在门槛上落过一次。"
            "门帘垂着。他转身出门。内门议事堂的灯还亮着。"
        ) * 3

        report = evaluate_payoff_ledger(text, chapter_position=1)

        assert report.finding.hook_hits == 0, (
            f"setting vocabulary still counted as hooks: {report.finding.detail}"
        )
        assert report.passed, report.finding.detail


class TestSingleCharacterSignalsArePinned:
    """Single-character signals are where this class of bug enters.

    A one-character substring matches inside every compound that contains it,
    so each one must be a reaction or a turn — something that only happens —
    and never a noun. Pinning the set forces the next addition to be a
    deliberate decision rather than an unnoticed genre landmine.
    """

    def test_only_reaction_and_turn_characters_are_single_char_signals(self) -> None:
        single = {s for s in _HOOK_SIGNALS if len(s) == 1}
        assert single == {"却", "愣", "震"}, (
            "adding a single-character hook signal saturates any genre whose "
            "vocabulary contains it — see 「门」 in 宗门 stories"
        )


class TestRealHooksStillCount:
    def test_a_door_event_is_still_a_hook(self) -> None:
        """The signal's intent — something arrives — must survive the fix."""

        text = "他正要收账，忽然有人叩门。" + "账房里静得出奇。" * 20

        report = evaluate_payoff_ledger(text, chapter_position=1)
        assert report.finding.hook_hits >= 1

    @pytest.mark.parametrize("phrase", ["叩门", "敲门", "推门", "门开了"])
    def test_door_event_phrases_are_signals(self, phrase: str) -> None:
        assert any(signal in phrase for signal in _HOOK_SIGNALS), (
            f"{phrase} is a door *event* and should still register"
        )

    def test_non_door_hooks_are_untouched(self) -> None:
        text = "他没想到会这样。突然，脚步声近了。他回头，愣住。" * 6

        report = evaluate_payoff_ledger(text, chapter_position=1)
        assert report.finding.hook_hits >= 5

    def test_a_genuinely_hook_only_chapter_is_still_caught(self) -> None:
        """The gate must keep its teeth on the case it exists for."""

        text = "他突然回头。脚步声。他愣住，震了一下。究竟是谁？" * 8

        report = evaluate_payoff_ledger(text, chapter_position=1)
        assert not report.passed
        assert report.finding.code in {"PAYOFF_HOOK_ONLY", "PAYOFF_LEDGER_LOW"}
